//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 凶屋地图.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<select name=\"d\" id=\"d\" style=\"width:165px\">\r\n                                   " +
            "                 <option value=\"\">所有地區</option><option value=\"H\">------------香港區" +
            "------------</option><option value=\"HA\">香港仔</option><option value=\"HC\">中環</optio" +
            "n><option value=\"HCB\" selected=\"\">銅鑼灣</option><option value=\"HCW\">柴灣</option><op" +
            "tion value=\"HHV\">跑馬地</option><option value=\"HKT\">堅尼地城</option><option value=\"HMC" +
            "\">中半山</option><option value=\"HME\">東半山</option><option value=\"HMW\">西半山</option><o" +
            "ption value=\"HNP\">北角</option><option value=\"HPF\">薄扶林</option><option value=\"HQB\"" +
            ">鰂魚涌</option><option value=\"HRB\">淺水灣</option><option value=\"HSK\">筲箕灣</option><op" +
            "tion value=\"HSS\">小西灣</option><option value=\"HSW\">上環</option><option value=\"HSY\">" +
            "西營盤</option><option value=\"HWC\">灣仔</option><option value=\"K\">------------九龍區----" +
            "--------</option><option value=\"KCS\">長沙灣</option><option value=\"KDH\">鑽石山</option" +
            "><option value=\"KHH\">紅磡</option><option value=\"KHM\">何文田</option><option value=\"K" +
            "KB\">九龍灣</option><option value=\"KKC\">九龍城</option><option value=\"KKL\">九龍塘</option>" +
            "<option value=\"KKT\">觀塘</option><option value=\"KLC\">荔枝角 / 美孚</option><option valu" +
            "e=\"KLT\">藍田</option><option value=\"KMK\">旺角</option><option value=\"KNT\">牛頭角</optio" +
            "n><option value=\"KSK\">石硤尾 / 又一村</option><option value=\"KSS\">深水步</option><option " +
            "value=\"KTK\">大角咀</option><option value=\"KTS\">尖沙咀</option><option value=\"KTW\">土瓜灣<" +
            "/option><option value=\"KWT\">黃大仙</option><option value=\"KYM\">油麻地</option><option " +
            "value=\"N\">------------新界區------------</option><option value=\"NFL\">粉嶺</option><op" +
            "tion value=\"NKC\">葵涌</option><option value=\"NMO\">馬鞍山</option><option value=\"NSK\">" +
            "西貢</option><option value=\"NSS\">上水</option><option value=\"NST\">沙田</option><option" +
            " value=\"NTC\">東涌</option><option value=\"NTK\">將軍澳</option><option value=\"NTM\">屯門</" +
            "option><option value=\"NTP\">大埔</option><option value=\"NTS\">天水圍</option><option va" +
            "lue=\"NTW\">荃灣</option><option value=\"NYL\">元朗</option>                            " +
            "                        </select>")]
        public string Area {
            get {
                return ((string)(this["Area"]));
            }
            set {
                this["Area"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;uid=root;pwd=123456;database=awol;Charset=utf8;ConnectionTimeout" +
            "=60;")]
        public string DBCon_local {
            get {
                return ((string)(this["DBCon_local"]));
            }
            set {
                this["DBCon_local"] = value;
            }
        }
    }
}
